#spring:
#  datasource:
#    url: jdbc:postgresql://db:5432/player_db
#    username: player_db
#    password: brownisgoat
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect